braille = {
    ((False, False),
    (False, False),
    (False, False)): "⠀",
    ((True, False),
    (False, False),
    (False, False)): "⠁",
    ((False, False),
    (True, False),
    (False, False)): "⠂",
    ((True, False),
    (True, False),
    (False, False)): "⠃",
    ((False, False),
    (False, False),
    (True, False)): "⠄",
    ((True, False),
    (False, False),
    (True, False)): "⠅",
    ((False, False),
    (True, False),
    (True, False)): "⠆",
    ((True, False),
    (True, False),
    (True, False)): "⠇",
    ((False, True),
    (False, False),
    (False, False)): "⠈",
    ((True, True),
    (False, False),
    (False, False)): "⠉",
    ((False, True),
    (True, False),
    (False, False)): "⠊",
    ((True, True),
    (True, False),
    (False, False)): "⠋",
    ((False, True),
    (False, False),
    (True, False)): "⠌",
    ((True, True),
    (False, False),
    (True, False)): "⠍",
    ((False, True),
    (True, False),
    (True, False)): "⠎",
    ((True, True),
    (True, False),
    (True, False)): "⠏",
    ((False, False),
    (False, True),
    (False, False)): "⠐",
    ((True, False),
    (False, True),
    (False, False)): "⠑",
    ((False, False),
    (True, True),
    (False, False)): "⠒",
    ((True, False),
    (True, True),
    (False, False)): "⠓",
    ((False, False),
    (False, True),
    (True, False)): "⠔",
    ((True, False),
    (False, True),
    (True, False)): "⠕",
    ((False, False),
    (True, True),
    (True, False)): "⠖",
    ((True, False),
    (True, True),
    (True, False)): "⠗",
    ((False, True),
    (False, True),
    (False, False)): "⠘",
    ((True, True),
    (False, True),
    (False, False)): "⠙",
    ((False, True),
    (True, True),
    (False, False)): "⠚",
    ((True, True),
    (True, True),
    (False, False)): "⠛",
    ((False, True),
    (False, True),
    (True, False)): "⠜",
    ((True, True),
    (False, True),
    (True, False)): "⠝",
    ((False, True),
    (True, True),
    (True, False)): "⠞",
    ((True, True),
    (True, True),
    (True, False)): "⠟",
    ((False, False),
    (False, False),
    (False, True)): "⠠",
    ((True, False),
    (False, False),
    (False, True)): "⠡",
    ((False, False),
    (True, False),
    (False, True)): "⠢",
    ((True, False),
    (True, False),
    (False, True)): "⠣",
    ((False, False),
    (False, False),
    (True, True)): "⠤",
    ((True, False),
    (False, False),
    (True, True)): "⠥",
    ((False, False),
    (True, False),
    (True, True)): "⠦",
    ((True, False),
    (True, False),
    (True, True)): "⠧",
    ((False, True),
    (False, False),
    (False, True)): "⠨",
    ((True, True),
    (False, False),
    (False, True)): "⠩",
    ((False, True),
    (True, False),
    (False, True)): "⠪",
    ((True, True),
    (True, False),
    (False, True)): "⠫",
    ((False, True),
    (False, False),
    (True, True)): "⠬",
    ((True, True),
    (False, False),
    (True, True)): "⠭",
    ((False, True),
    (True, False),
    (True, True)): "⠮",
    ((True, True),
    (True, False),
    (True, True)): "⠯",
    ((False, False),
    (False, True),
    (False, True)): "⠰",
    ((True, False),
    (False, True),
    (False, True)): "⠱",
    ((False, False),
    (True, True),
    (False, True)): "⠲",
    ((True, False),
    (True, True),
    (False, True)): "⠳",
    ((False, False),
    (False, True),
    (True, True)): "⠴",
    ((True, False),
    (False, True),
    (True, True)): "⠵",
    ((False, False),
    (True, True),
    (True, True)): "⠶",
    ((True, False),
    (True, True),
    (True, True)): "⠷",
    ((False, True),
    (False, True),
    (False, True)): "⠸",
    ((True, True),
    (False, True),
    (False, True)): "⠹",
    ((False, True),
    (True, True),
    (False, True)): "⠺",
    ((True, True),
    (True, True),
    (False, True)): "⠻",
    ((False, True),
    (False, True),
    (True, True)): "⠼",
    ((True, True),
    (False, True),
    (True, True)): "⠽",
    ((False, True),
    (True, True),
    (True, True)): "⠾",
    ((True, True),
    (True, True),
    (True, True)): "⠿",
}
blockGraphics1x2 = {
    (False, False): " ", 
    (False, True): "▄",
    (True, False): "▀",
    (True, True): "█"
}
blockGraphics2x2 = {
    
}